package(default_visibility = ["//visibility:public"])

py_library(
    name = "pack_image",
    srcs = ["pack_image.py"],
    imports = ["."],
)

py_test(
    name = "test_pack_image",
    srcs = ["test_pack_image.py"],
    deps = [":pack_image"],
)
