ifndef HDK_COMMON_DIR
$(error Source the pinned hdk_setup.sh first)
endif
include $(HDK_COMMON_DIR)/verif/tb/scripts/Makefile.header.inc
include $(HDK_COMMON_DIR)/verif/tb/scripts/Makefile.common.inc
